# MMios 签到模块
[rewrite_local]
^https:\/\/www\.mmios\.net\/wp-admin\/admin-ajax\.php url script-request-header https://raw.githubusercontent.com/.../mmios_checkin.js

[task_local]
30 8 * * * https://raw.githubusercontent.com/.../mmios_checkin.js, tag=MMios签到, enabled=true

[mitm]
hostname = www.mmios.net
